# Generated by Django 3.0.5 on 2020-04-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200411_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=25.99, max_digits=6),
            preserve_default=False,
        ),
    ]
