# Generated by Django 3.0.5 on 2020-04-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='photos/instructors')),
                ('description', models.TextField(blank=True)),
                ('email', models.CharField(max_length=100)),
                ('is_mvp', models.BooleanField(default=False)),
            ],
        ),
    ]
